### PR TITLE
Added suggestions for Institute/Courses/Language

### LINKED ISSUE #25: Auto-suggest form inputs like institute name/ course name/ languages.

### PR DESCRIPTION
**Pull request by AK-007**
Fixes #25

### CODE REVIEW

**Comment by AK-007** [comment]
@aswinzz Plz review.

**Comment by aswinzz** [comment]
Good

**Comment by aswinzz** [comment]
@AK-007  can you sent the screenshot? it is not working !

**Comment by AK-007** [comment]
@aswinzz Check this out.
lucidcv

**Comment by aswinzz** [comment]
@AK-007 it should be programming language :p

**Comment by AK-007** [comment]
@aswinzz Ohh.... 😄 I'll make a PR for that.

**Pull request merged**
